### ISSUE TITLE
自分のソフトのライセンスと、使用したライセンスの区別

### ISSUE THREAD

**Issue by forno** [yasu80/missileAttack#1]
Hi.
あなたのソフトウェアのライセンスをLICENSEファイルに書き込みますね。
さて、あなたが使用した他人のソフトのライセンスは通常READMEファイルなどのわかりやすいところに表示するだけにしておくのが混乱を招きづらいです。
なぜなら通常LICENSEファイルはあなたのソフトウェアのライセンスを示すものだからです。

READMEにLicenseの欄を設けて、そちらに何を使用したか羅列するほうがわかりやすくてよいですよ。
それに大抵のライセンスは見やすいところに表示することを要請しているのでReadmeに書くのがとても妥当なのです。

**Comment by yasu80** [comment]
Ja,
対処しました. 常識って大事ですね・・・
